---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-agent-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-agent-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["create", "delete", "describe", "get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-agent-role-binding
subjects:
- kind: ServiceAccount
  name: k8s-agent-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-agent-secret
type: Opaque
stringData:
  cluster-id: "05c3feaa-f647-442c-b007-0a1ddc4a1cd9"
  cluster-secret: "b7b4e5a3-4515-4224-9e6f-3f40e6771344"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-agent
  template:
    metadata:
      labels:
        app: k8s-agent
    spec:
      serviceAccountName: k8s-agent-sa
      containers:
      - name: k8s-agent
        image: k8s-agent:latest
        imagePullPolicy: Never
        env:
        - name: CLUSTER_ID
          valueFrom:
            secretKeyRef:
              name: k8s-agent-secret
              key: cluster-id
        - name: CLUSTER_SECRET
          valueFrom:
            secretKeyRef:
              name: k8s-agent-secret
              key: cluster-secret
        - name: ENDPOINT_URL
          value: "ws://172.16.1.5:4050/socket/kubernetes/clusters"
        volumeMounts:
        - name: kube-api-access
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: kube-api-access
        projected:
          sources:
          - serviceAccountToken:
              expirationSeconds: 3600
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
              - key: ca.crt
                path: ca.crt
          - downwardAPI:
              items:
              - path: namespace
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace